#!/usr/bin/racket
#lang racket
(display "enter height in inches")
(newline)
(define height (read))
(display "you said your height was ") (display height) (display " inches.")
(newline)
(display "enter weight in pounds")
(newline)
(define weight (read))
(newline)
(display "you said your weight was ") (display weight) (display " pounds.")
(newline)
(define (body-mass-index weight height)
  (define (square x)
    (* x x))
  (/ (* weight 703.0) (square height)))
(display "your body mass index is ") (display (body-mass-index weight height))
(newline)
(define (bmi-class bmi)
  (cond ((< bmi 18.5)                       "underweight")
        ((and (>= bmi 18.5) (< bmi 24.9))   "normal")
        ((and (>= bmi 25.0) (< bmi 29.9))   "overweight")
        ((> bmi 30.0)                        "obese")))
(display "this is considered to be ") (display (bmi-class (body-mass-index weight height))) (display ".")
(newline)
(display "all done.")
